apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: hello-pipeline-run
  labels:
    app: hello-example
spec:
  pipelineRef:
    name: hello-pipeline
  params:
    - name: message
      value: "Hello from my first PipelineRun!"


